/* 작성: GPT(Codex·메인북) · 2026-09-26 — 주간계획은 부모 확인 후 참고한다. */
(function(){
  'use strict';
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const api=()=>window.HW_API||TUTOR_API, id=()=>DB.viewer?DB.lid:learnerId(), role=()=>DB.viewer?'parent':'child';
  const key=()=> 'school_plan_job_v1:'+id();
  let state={plans:[]}, busy=false, selected=null, message='', pollTimer=null, pollCount=0, loadedAt=0, owner='';
  const shell=()=>document.getElementById('school-plan-dialog');
  const uid=()=>crypto.randomUUID();
  async function request(path,options){const c=new AbortController(),t=setTimeout(()=>c.abort(),25000);try{const r=await fetch(api()+path,{...options,signal:c.signal,cache:'no-store'});const j=await r.json();if(!r.ok){const e=new Error(j.error||'학교 계획을 확인하지 못했어요.');e.status=r.status;throw e;}return j;}finally{clearTimeout(t);}}
  function keep(j){state={plans:structuredClone(Array.isArray(j.plans)?j.plans:[]),revision:j.revision};DB.schoolPlans=structuredClone(state.plans);saveDB();loadedAt=Date.now();}
  window.fetchSchoolPlans=async function(force){if(!navigator.onLine||busy)return false;if(!force&&owner===id()&&Date.now()-loadedAt<60000)return false;const current=id();try{const j=await request('/api/school-plan?id='+encodeURIComponent(current)+'&role='+role());if(id()!==current)return false;owner=current;keep(j);return true;}catch(_){return false;}};
  window.schoolPlanSummaryHTML=function(){const day=todayKey(),p=(DB.schoolPlans||[]).filter(p=>p.status==='confirmed'&&p.weekStart<=day&&p.weekEnd>=day).sort((a,b)=>(b.confirmedAt||0)-(a.confirmedAt||0))[0];return `<div class="card school-summary"><h3>📅 학교와 이어지는 배움</h3><p class="dim">${p?esc(p.weekStart)+' ~ '+esc(p.weekEnd)+' · 확인한 주간계획':DB.viewer?'주간계획표 사진을 올리고 내용을 확인해 주세요.':'이번 주 학교 계획을 기다리고 있어요.'}</p><button class="wpill" onclick="openSchoolPlan()">${DB.viewer?'학교 계획표 확인·올리기':'이번 주 학교 계획 보기'}</button></div>`;};
  function units(value){return `<option value="">연결할 단원 확인 필요</option>`+UNITS.filter(u=>u.subj==='math'&&(u.grade||3)===3).map(u=>`<option value="${esc(u.id)}"${u.id===value?' selected':''}>${esc(u.name)}</option>`).join('');}
  function row(s,i){return `<fieldset class="school-row"><legend>${i+1}번째 수업</legend><label>과목<select name="subject-${i}">${[['math','수학'],['korean','국어'],['other','그 밖의 과목']].map(([v,n])=>`<option value="${v}"${s.subject===v?' selected':''}>${n}</option>`).join('')}</select></label><label>계획표에 적힌 단원<input name="unitLabel-${i}" maxlength="100" value="${esc(s.unitLabel)}"></label><label>쪽수<input name="pages-${i}" maxlength="60" value="${esc(s.pages)}" placeholder="모르면 비워 두세요"></label><label>앱 수학 단원 연결<select name="unitId-${i}">${units(s.unitId)}</select></label><label>메모<textarea name="notes-${i}" maxlength="300">${esc(s.notes)}</textarea></label><p class="dim">수학이 아니거나 단원이 불분명하면 연결하지 않아도 돼요.</p></fieldset>`;}
  function edit(){const p=state.plans.find(x=>x.id===selected);if(!p)return '';return `<form id="school-confirm-form" class="card"><h3>${p.status==='confirmed'?'확인한 계획 수정':'사진에서 읽은 내용 확인'}</h3><p class="dim">원본과 비교해 고쳐 주세요. 학교의 예정 진도이며 실제로 배웠는지와 이해도는 별도로 살펴봐요.</p>${(p.warnings||[]).map(w=>`<p class="school-warning">${esc(({date_unclear:'날짜가 불분명해요. 원본에서 확인해 주세요.',grade_unclear:'학년을 확인해 주세요.',text_unclear:'일부 글씨가 흐려요. 수업 내용을 확인해 주세요.',not_weekly_plan:'주간계획표인지 확인해 주세요.'})[w]||w)}</p>`).join('')}<div class="school-date-grid"><label>시작 날짜<input type="date" name="weekStart" value="${esc(p.weekStart)}" required></label><label>끝 날짜<input type="date" name="weekEnd" value="${esc(p.weekEnd)}" required></label></div><label>학년<select name="grade" required><option value="">확인해 주세요</option>${[1,2,3,4,5,6].map(g=>`<option value="${g}"${Number(p.grade)===g?' selected':''}>${g}학년</option>`).join('')}</select></label>${(p.subjects||[]).map(row).join('')}<button type="button" class="wpill" data-school="add-row">＋ 수업 한 줄 추가</button><label class="school-check"><input name="verified" type="checkbox" required> 날짜와 학년, 수업 내용을 원본과 비교했어요.</label><button class="bigbtn" type="submit"${busy?' disabled':''}>확인하고 학교 계획 저장</button><button type="button" class="bigbtn ghost" data-school="cancel-edit">나중에 확인</button></form>`;}
  function render(){const el=shell();if(!el)return;const stored=localStorage.getItem(key());el.innerHTML=`<section class="school-inner" role="dialog" aria-modal="true" aria-label="학교 주간계획"><header><button class="wpill" data-school="close" aria-label="학교 계획 닫기">←</button><h2>학교 주간계획</h2></header><p class="dim">이번 주 학교에서 배울 것과 앱에서 연습할 것을 함께 봐요.</p><div class="school-message" role="status">${esc(message)}</div>${DB.viewer?`<div class="card"><h3>📸 매주 한 번, 계획표 사진</h3><p class="dim">분석을 누르면 사진이 AI 분석 서버로 전송됩니다. 이름·연락처가 나오지 않게 수업 부분만 찍어 주세요. 분석 후 임시 사진은 제거하고 확인한 수업 내용만 보관합니다.</p><label class="school-upload">사진 선택 (최대 2장)<input id="school-photos" type="file" accept="image/jpeg,image/png,image/webp" multiple${busy?' disabled':''}></label><div id="school-photo-preview"></div><button class="bigbtn" data-school="extract"${busy?' disabled':''}>${busy?'처리 중…':'사진에서 수업 내용 읽기'}</button>${stored?'<button class="wpill" data-school="resume">진행 중인 사진 분석 확인</button>':''}<button class="linkbtn" data-school="manual"${busy?' disabled':''}>사진 없이 직접 입력</button></div>`:''}${selected&&DB.viewer?edit():''}${state.plans.length?state.plans.map(p=>`<div class="card"><div class="school-badge">${p.status==='confirmed'?'✓ 부모 확인 완료':'확인 전 초안'}</div><h3>${esc(p.weekStart||'날짜 확인 필요')} ~ ${esc(p.weekEnd||'')}</h3><p class="dim">${p.grade?esc(p.grade)+'학년':'학년 확인 필요'} · ${p.status==='confirmed'?'학교 예정 진도':'확인 전에는 과제에 반영하지 않아요'}</p>${(p.subjects||[]).map(s=>`<p><b>${({math:'수학',korean:'국어',other:'그 밖의 과목'})[s.subject]||'수업'}</b> ${esc(s.unitLabel)} ${s.pages?'· '+esc(s.pages):''}</p>`).join('')}${DB.viewer?`<button class="wpill" data-school="edit" data-id="${esc(p.id)}"${busy?' disabled':''}>${p.status==='confirmed'?'수정하기':'확인·수정하기'}</button>`:''}</div>`).join(''):'<div class="card"><p>아직 올린 학교 계획이 없어요.</p></div>'}</section>`;}
  let photoFiles=[];
  function captureForm(){const p=state.plans.find(x=>x.id===selected),f=document.getElementById('school-confirm-form');if(!p||!f)return;const d=new FormData(f);p.weekStart=d.get('weekStart')||null;p.weekEnd=d.get('weekEnd')||null;p.grade=Number(d.get('grade'))||null;p.subjects=p.subjects.map((s,i)=>({subject:d.get('subject-'+i),unitLabel:String(d.get('unitLabel-'+i)||''),pages:String(d.get('pages-'+i)||''),unitId:d.get('subject-'+i)==='math'?(d.get('unitId-'+i)||null):null,notes:String(d.get('notes-'+i)||'')}));}
  async function encodePhoto(f){if(f.size>20*1024*1024)throw new Error('사진이 너무 커요. 수업 부분만 다시 찍어 주세요.');if(!/^image\/(jpeg|png|webp)$/.test(f.type))throw new Error('JPG, PNG, WEBP 사진을 선택해 주세요.');return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('사진을 읽지 못했어요.'));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('사진 형식을 확인해 주세요.'));img.onload=()=>{try{const sc=Math.min(1,1600/Math.max(img.width,img.height)),cv=document.createElement('canvas');cv.width=Math.round(img.width*sc);cv.height=Math.round(img.height*sc);cv.getContext('2d').drawImage(img,0,0,cv.width,cv.height);let q=.85,u=cv.toDataURL('image/jpeg',q);while(u.length>1100000&&q>.35){q-=.1;u=cv.toDataURL('image/jpeg',q);}if(u.length>1300000)throw new Error('사진이 너무 커요. 수업 부분만 잘라 주세요.');resolve(u);}catch(e){reject(e);}};img.src=reader.result;};reader.readAsDataURL(f);});}
  async function poll(job){clearTimeout(pollTimer);try{const j=await request('/api/school-plan?id='+encodeURIComponent(id())+'&role='+role()+'&job='+encodeURIComponent(job));keep(j);if(j.job?.status==='done'){localStorage.removeItem(key());busy=false;selected=j.job.planId||null;message='내용을 읽었어요. 날짜와 수업 내용을 확인해 주세요.';render();return;}if(j.job?.status==='error'){localStorage.removeItem(key());busy=false;message=j.job.error||'사진을 읽지 못했어요. 다시 찍거나 직접 입력해 주세요.';render();return;}}catch(e){message='아직 연결을 확인하지 못했어요. 잠시 후 다시 확인합니다.';}if(++pollCount>=60||!shell()){busy=false;message='아직 분석 중이에요. 나중에 이 화면에서 진행 중인 분석을 확인해 주세요.';render();return;}pollTimer=setTimeout(()=>poll(job),2000);}
  async function extract(){if(busy)return;if(!DB.viewer)return;if(!photoFiles.length){message='먼저 계획표 사진을 선택해 주세요.';render();return;}busy=true;message='사진을 보내고 있어요…';const files=photoFiles.slice(0,2);render();try{const images=await Promise.all(files.map(encodePhoto)),job=uid();localStorage.setItem(key(),job);const j=await request('/api/school-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id(),role:role(),action:'extract',requestId:job,images})});photoFiles=[];message='선생님이 계획표를 읽고 있어요. 다른 화면을 보고 와도 괜찮아요.';render();pollCount=0;poll(j.jobId||job);}catch(e){busy=false;message=e.message||'사진을 보내지 못했어요.';render();}}
  async function confirmPlan(event){event.preventDefault();if(busy||!DB.viewer)return;captureForm();const p=state.plans.find(x=>x.id===selected);if(!p)return;if(!p.weekStart||!p.weekEnd||p.weekEnd<p.weekStart||!p.grade){message='날짜 범위와 학년을 확인해 주세요.';render();return;}busy=true;message='확인한 계획을 저장하고 있어요…';render();try{const body={id:id(),role:role(),action:'confirm',requestId:uid(),planId:p.id,version:p.version,plan:{weekStart:p.weekStart,weekEnd:p.weekEnd,grade:p.grade,subjects:p.subjects}};const j=await request('/api/school-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});keep(j);selected=null;message='저장했어요. 다음에 만드는 오늘 과제부터 확인된 학교 단원을 참고해요.';}catch(e){message=e.message;if(e.status===409){try{const j=await request('/api/school-plan?id='+encodeURIComponent(id())+'&role='+role());keep(j);selected=null;message='다른 요청에서 저장된 최신 계획을 불러왔어요. 내용을 확인해 주세요.';}catch(_){}}}finally{busy=false;render();}}
  window.openSchoolPlan=async function(){if(shell())return;message='학교 계획을 불러오고 있어요…';selected=null;const el=document.createElement('div');el.id='school-plan-dialog';document.body.appendChild(el);el.addEventListener('submit',confirmPlan);el.addEventListener('change',e=>{if(e.target.id==='school-photos'){photoFiles=[...e.target.files].slice(0,2);const p=document.getElementById('school-photo-preview');p.textContent=photoFiles.length+'장 선택됨 · 날짜와 수업 부분이 선명한지 확인해 주세요.';}});el.addEventListener('click',async e=>{const b=e.target.closest('[data-school]');if(!b)return;const act=b.dataset.school;if(act==='close'){clearTimeout(pollTimer);busy=false;el.remove();return;}if(act==='extract')return extract();if(act==='edit'){selected=b.dataset.id;message='내용을 확인하고 저장해 주세요.';render();document.getElementById('school-confirm-form')?.scrollIntoView({block:'start'});}if(act==='cancel-edit'){selected=null;state.plans=structuredClone(DB.schoolPlans||[]);render();}if(act==='add-row'){captureForm();if(state.plans.find(p=>p.id===selected).subjects.length>=30){message='한 계획에는 수업을 30개까지 입력할 수 있어요.';render();return;}state.plans.find(p=>p.id===selected).subjects.push({subject:'math',unitLabel:'',pages:'',unitId:null,notes:''});render();}if(act==='resume'){const job=localStorage.getItem(key());if(job){busy=true;pollCount=0;message='분석 상태를 확인하고 있어요…';render();poll(job);}}if(act==='manual'){busy=true;message='빈 계획표를 준비하고 있어요…';render();try{const j=await request('/api/school-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id(),role:role(),action:'manual',requestId:uid()})});keep(j);selected=j.planId;message='날짜와 수업 내용을 입력해 주세요.';}catch(e){message=e.message;}finally{busy=false;render();}}});render();const ok=await fetchSchoolPlans(true);message=ok?'':'연결을 확인하지 못했어요. 저장된 계획이 있다면 보여드려요.';if(!ok)state={plans:structuredClone(DB.schoolPlans||[])};render();};
})();
